import React, { useState } from 'react';
import { 
  ShieldCheck, 
  Clock, 
  Search, 
  Filter, 
  Download, 
  CheckCircle2, 
  AlertTriangle,
  User,
  Hash
} from 'lucide-react';
import { AuditLogEntry } from '../../types';

interface AuditTrailViewProps {
  logs: AuditLogEntry[];
  onSelectWorkCode?: (workCode: string) => void;
}

export const AuditTrailView: React.FC<AuditTrailViewProps> = ({
  logs,
  onSelectWorkCode,
}) => {
  const [filterAction, setFilterAction] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  const filteredLogs = logs.filter((log) => {
    if (filterAction !== 'ALL' && log.action !== filterAction) return false;
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase().trim();
      return (
        log.workCode.toLowerCase().includes(q) ||
        log.userName.toLowerCase().includes(q) ||
        log.details.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const exportAuditCsv = () => {
    const headers = 'ID,WorkCode,Timestamp,UserRole,UserName,Action,Details,VerificationHash\n';
    const rows = logs.map(l => 
      `"${l.id}","${l.workCode}","${l.timestamp}","${l.userRole}","${l.userName}","${l.action}","${l.details}","${l.verificationHash}"`
    ).join('\n');

    const blob = new Blob([headers + rows], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MPLADS_SENTINEL_AUDIT_TRAIL_${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold tracking-tight text-white font-sans">
              Immutable Governance Audit Ledger
            </h1>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-emerald-950/60 border border-emerald-800 text-emerald-300">
              Cryptographically Verified
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl">
            Chronological audit log tracking alert generation, supervisory views, assignment dispatches, field inspection notes, and official status resolutions.
          </p>
        </div>

        <button
          onClick={exportAuditCsv}
          className="inline-flex items-center gap-2 px-3.5 py-2 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-700 text-xs font-medium text-slate-200 hover:text-white transition-colors cursor-pointer"
        >
          <Download className="w-3.5 h-3.5 text-cyan-400" />
          <span>Export Ledger (CSV)</span>
        </button>
      </div>

      {/* Filter Row */}
      <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 flex flex-wrap items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-3">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search work code, officer, or keyword..."
            className="w-64 px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500"
          />

          <select
            value={filterAction}
            onChange={(e) => setFilterAction(e.target.value)}
            className="px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-slate-300 focus:outline-none"
          >
            <option value="ALL">All Governance Actions</option>
            <option value="ALERT_GENERATED">Alert Generated by AI</option>
            <option value="INSPECTION_SCHEDULED">Field Inspection Scheduled</option>
            <option value="STATUS_UPDATED">Status Adjusted</option>
            <option value="COMMENT_ADDED">Official Remark Added</option>
            <option value="EVIDENCE_UPLOADED">Evidence Uploaded</option>
          </select>
        </div>

        <span className="font-mono text-slate-400 text-[11px]">
          {filteredLogs.length} Chronological Entries
        </span>
      </div>

      {/* Visual Timeline Stream */}
      <div className="space-y-3 relative before:absolute before:inset-0 before:left-5 before:w-0.5 before:bg-slate-800">
        {filteredLogs.map((log) => (
          <div
            key={log.id}
            className="relative flex items-start gap-4 pl-3 group"
          >
            {/* Timeline node */}
            <div className="w-4 h-4 rounded-full bg-slate-900 border-2 border-indigo-500 mt-3 z-10 shrink-0 group-hover:scale-125 transition-transform" />

            {/* Event Box */}
            <div className="flex-1 p-4 rounded-xl bg-slate-900/90 border border-slate-800 hover:border-indigo-500/40 transition-colors space-y-2 shadow-md">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => onSelectWorkCode && onSelectWorkCode(log.workCode)}
                    className="font-mono font-bold text-xs text-cyan-400 hover:underline"
                  >
                    {log.workCode}
                  </button>
                  <span className="text-slate-600">·</span>
                  <span className="text-xs font-semibold text-white">
                    {log.action.replace('_', ' ')}
                  </span>
                  <span className="text-slate-600">·</span>
                  <span className="text-xs text-slate-400 flex items-center gap-1">
                    <User className="w-3 h-3 text-indigo-400" />
                    {log.userName} ({log.userRole})
                  </span>
                </div>

                <div className="flex items-center gap-2 font-mono text-[11px] text-slate-400">
                  <Clock className="w-3 h-3" />
                  <span>{log.timestamp}</span>
                </div>
              </div>

              <p className="text-xs text-slate-200 leading-relaxed font-sans">
                {log.details}
              </p>

              <div className="pt-2 border-t border-slate-800/80 flex items-center justify-between text-[10px] font-mono text-slate-400">
                <span className="flex items-center gap-1 text-slate-400">
                  <Hash className="w-3 h-3 text-slate-400" />
                  {log.verificationHash}
                </span>
                <span className="text-emerald-400">✓ Cryptographically Sealed</span>
              </div>
            </div>
          </div>
        ))}
      </div>

    </div>
  );
};
